version: "3"
services:
  pricing-api:
    build:
      context: .
      dockerfile: services/pricing/Dockerfile
    depends_on:
      - "pricing-postgres"
      - "pricing-redis"
  pricing-postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: pricing
      POSTGRES_PASSWORD: 04b76987bf0649519ef42136419d442e
  pricing-redis:
    image: "redis:alpine"
  ride-api:
    build:
      context: .
      dockerfile: services/ride/Dockerfile
    ports:
      - "3000:3000"
  # pg-admin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "root@postgresql.org"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   ports:
  #     - "16543:80"
