version: "3"
services:
  playground:
    build:
      context: .
      dockerfile: playground/Dockerfile
    ports:
      - "3000:3000"
  pricing-api:
    build:
      context: .
      dockerfile: services/pricing/Dockerfile
    depends_on:
      - "pricing-postgres"
      - "pricing-redis"
  pricing-postgres:
    image: "postgres:12.1-alpine"
    environment:
      POSTGRES_DB: pricing
      POSTGRES_PASSWORD: 04b76987bf0649519ef42136419d442e
  pricing-redis:
    image: "redis:6.0-rc1-alpine"
  ride-api:
    build:
      context: .
      dockerfile: services/ride/Dockerfile
    ports:
      - "3001:3001"
  ride-redis:
    image: "redis:6.0-rc1-alpine"
  ride-postgres:
    image: "postgres:12.1-alpine"
    environment:
      POSTGRES_DB: ride
      POSTGRES_PASSWORD: 122ff0fb63174b0f8496ec3f30c64470
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@postgresql.org"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "3002:80"
